[package]
name = "bfs"
version = "0.1.0"
authors = ["mazur <maksym.mazur@sizmek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
